import type { TFunction } from "i18next";

export function postServiceErrorMessage(t: TFunction, error: unknown) {
  const message = error instanceof Error
    ? error.message
    : error && typeof error === "object" && "message" in error && typeof error.message === "string"
      ? error.message
      : "";
  const keys: Record<string, string> = {
    "Select a business partner in this workspace": "selectBusinessPartner",
    "Select an active delivery merchant": "selectMerchant",
    "Recipient phone and delivery address are required": "recipientRequired",
    "COD amount must be greater than zero": "cashOnDeliveryCodRequired",
    "Select an active courier": "selectCourier",
    "Select at least one shipment": "selectShipment",
    "Only unassigned, received, or postponed shipments can be dispatched": "shipmentNotDispatchable",
    "Only returned shipments can be transferred": "returnedTransferOnly",
    "A received return cannot be transferred": "receivedReturnTransferBlocked",
    "Only an administrator can receive a returned post": "returnReceiptAdminOnly",
    "Only returned posts can be received": "returnReceiptOnly",
    "This returned post has already been received": "returnAlreadyReceived",
    "This post has changed. Refresh it before receiving its return": "returnReceiptChanged",
    "Select a different courier": "differentCourierRequired",
    "Shipment not found": "shipmentNotFound",
    "A completed shipment cannot be changed. Record an adjustment instead.": "completedShipment",
    "A reason is required for this status": "reasonRequired",
    "Assign the shipment to a courier first": "assignCourierFirst",
    "A courier can only update shipments assigned to them": "courierAssignmentOnly",
    "Only cash-on-delivery posts can have a COD change requested": "codChangeCashOnly",
    "COD changes can only be requested for an assigned or postponed post": "codChangeStatusOnly",
    "A courier can only request a COD change for posts assigned to them": "codChangeCourierOnly",
    "Requested COD amount must differ from the current COD amount": "codChangeMustDiffer",
    "This post already has a pending COD change request": "codChangeAlreadyPending",
    "Review the pending COD change before marking the post delivered": "codChangePendingDeliveryBlocked",
    "COD change request not found": "codChangeRequestNotFound",
    "This COD change request has already been reviewed": "codChangeAlreadyReviewed",
    "Only an administrator can review a COD change request": "codChangeReviewAdminOnly",
    "This COD change request can no longer be approved": "codChangeNoLongerReviewable",
    "Review the pending COD change before changing the post COD details": "codChangePendingEditBlocked",
    "Only electronically prepaid posts can have a recipient payout change requested": "recipientPayoutChangePrepaidOnly",
    "Recipient payout changes can only be requested for an assigned or postponed post": "recipientPayoutChangeStatusOnly",
    "A courier can only request a recipient payout change for posts assigned to them": "recipientPayoutChangeCourierOnly",
    "Requested recipient payout amount must differ from the current recipient payout amount": "recipientPayoutChangeMustDiffer",
    "Requested recipient payout amount must be zero or greater": "recipientPayoutChangeAmountInvalid",
    "Approved recipient payout amount must be zero or greater": "recipientPayoutChangeAmountInvalid",
    "This post already has a pending recipient payout change request": "recipientPayoutChangeAlreadyPending",
    "Review the pending recipient payout change before marking the post delivered": "recipientPayoutChangePendingDeliveryBlocked",
    "Recipient payout change request not found": "recipientPayoutChangeRequestNotFound",
    "This recipient payout change request has already been reviewed": "recipientPayoutChangeAlreadyReviewed",
    "Only an administrator can review a recipient payout change request": "recipientPayoutChangeReviewAdminOnly",
    "This recipient payout change request can no longer be approved": "recipientPayoutChangeNoLongerReviewable",
    "Review the pending recipient payout change before changing the post payout details": "recipientPayoutChangePendingEditBlocked",
    "Settlement amount cannot exceed the outstanding balance": "amountExceedsBalance",
    "Explain a partial settlement before confirming it": "partialExplanationRequired",
    "Courier not found": "courierNotFound",
    "Merchant not found": "merchantNotFound",
    "A merchant with delivery history cannot be permanently deleted. Make it inactive instead.": "merchantDeleteHistory",
    "The post has no outstanding amount to settle": "postNoOutstanding",
    "Post created but assignment could not be completed. Retry to finish assigning the same post.": "postCreatedAssignmentPending",
    "This post is no longer available for create and dispatch": "createAndDispatchUnavailable",
    "This create-and-dispatch operation cannot be resumed": "createAndDispatchUnavailable",
    "Only an administrator can edit a received post": "adminEditReceivedOnly",
    "Only received posts can be edited without dispatch": "receivedEditStatusOnly",
    "This post has changed. Refresh it before editing": "receivedEditChanged",
    "Only an administrator can edit and redispatch a post": "adminRedispatchOnly",
    "Only received, assigned, or postponed posts can be edited and redispatched": "redispatchStatusOnly",
    "This post has changed. Refresh it before editing and redispatching": "redispatchChanged",
    "This admin redispatch operation cannot be resumed": "redispatchUnavailable",
    "Only an administrator can correct a delivered COD amount": "deliveredCodCorrectionAdminOnly",
    "Corrected COD amount must be greater than zero": "deliveredCodCorrectionAmountInvalid",
    "Corrected COD amount must differ from the current COD amount": "deliveredCodCorrectionMustDiffer",
    "Only delivered cash-on-delivery posts can have their COD corrected": "deliveredCodCorrectionStatusOnly",
    "Both related settlement obligations must still be fully outstanding": "deliveredCodCorrectionSettlementStarted",
    "This post has changed. Refresh it before correcting the COD": "deliveredCodCorrectionChanged",
    "Connect to the internet before correcting a delivered COD amount": "deliveredCodCorrectionOnlineRequired",
    "This delivered COD correction operation cannot be reused": "deliveredCodCorrectionUnavailable",
    "Only an administrator can correct a delivered recipient payout amount": "deliveredRecipientPayoutCorrectionAdminOnly",
    "Corrected recipient payout amount must be zero or greater": "deliveredRecipientPayoutCorrectionAmountInvalid",
    "Corrected recipient payout amount must differ from the current recipient payout amount": "deliveredRecipientPayoutCorrectionMustDiffer",
    "Only delivered courier-funded electronically prepaid posts can have their recipient payout corrected": "deliveredRecipientPayoutCorrectionStatusOnly",
    "Courier reimbursement and merchant repayment must still be fully outstanding": "deliveredRecipientPayoutCorrectionSettlementStarted",
    "This post has changed. Refresh it before correcting the recipient payout": "deliveredRecipientPayoutCorrectionChanged",
    "Connect to the internet before correcting a delivered recipient payout": "deliveredRecipientPayoutCorrectionOnlineRequired",
    "This delivered recipient payout correction operation cannot be reused": "deliveredRecipientPayoutCorrectionUnavailable",
  };
  return keys[message] ? t(`postService.errors.${keys[message]}`) : message || t("postService.errors.generic");
}

