CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  name text NOT NULL,
  email text NULL,
  phone text NULL,
  gender text NULL,
  role text NOT NULL,
  location text NULL,
  joining_date date NOT NULL DEFAULT CURRENT_DATE,
  salary numeric NOT NULL DEFAULT 0,
  salary_currency text NOT NULL DEFAULT 'usd'::text,
  version integer NOT NULL DEFAULT 1,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  has_dividends boolean NULL DEFAULT false,
  dividend_type text NULL,
  dividend_amount numeric NULL DEFAULT 0,
  dividend_currency text NULL DEFAULT 'usd'::text,
  salary_payday integer NULL DEFAULT 30,
  dividend_payday integer NULL DEFAULT 30,
  is_fired boolean NULL DEFAULT false,
  linked_user_id uuid NULL,
  PRIMARY KEY (id)
);
