CREATE TABLE public.installment_sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  sale_no text NOT NULL,
  customer_business_partner_id uuid NOT NULL,
  customer_name_snapshot text NOT NULL,
  description text NOT NULL,
  notes text NULL,
  currency text NOT NULL,
  acquisition_cost numeric NOT NULL,
  total_sale_price numeric NOT NULL,
  gross_profit numeric NOT NULL,
  down_payment_amount numeric NOT NULL DEFAULT 0,
  customer_paid_amount numeric NOT NULL DEFAULT 0,
  customer_balance_amount numeric NOT NULL,
  installment_count integer NOT NULL,
  has_installment_count boolean NOT NULL DEFAULT true,
  installment_frequency text NOT NULL,
  first_due_date timestamp without time zone NULL,
  next_due_date timestamp without time zone NULL,
  status text NOT NULL,
  cancelled_at timestamp with time zone NULL,
  cancelled_by uuid NULL,
  cancellation_reason text NULL,
  created_by uuid NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  is_deleted boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);
