CREATE TABLE public.loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  sale_id uuid NULL,
  loan_no text NOT NULL,
  source text NOT NULL,
  borrower_name text NOT NULL,
  borrower_phone text NOT NULL,
  borrower_address text NOT NULL,
  borrower_national_id text NOT NULL,
  principal_amount numeric NOT NULL,
  total_paid_amount numeric NOT NULL DEFAULT 0,
  balance_amount numeric NOT NULL,
  settlement_currency text NOT NULL,
  installment_count integer NOT NULL,
  installment_frequency text NOT NULL,
  first_due_date date NOT NULL,
  next_due_date date NULL,
  status text NOT NULL,
  notes text NULL,
  created_by uuid NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  is_deleted boolean NOT NULL DEFAULT false,
  overdue_reminder_snoozed_at timestamp with time zone NULL,
  overdue_reminder_snoozed_for_due_date date NULL,
  PRIMARY KEY (id)
);
