CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_by uuid NULL,
  sku character varying NOT NULL,
  name character varying NOT NULL,
  description text NULL DEFAULT ''::text,
  category character varying NULL,
  price numeric NOT NULL DEFAULT 0,
  cost_price numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 0,
  min_stock_level integer NOT NULL DEFAULT 10,
  unit character varying NOT NULL DEFAULT 'pcs'::character varying,
  image_url text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1,
  is_deleted boolean NOT NULL DEFAULT false,
  workspace_id uuid NULL,
  category_id uuid NULL,
  currency text NOT NULL DEFAULT 'usd'::text,
  can_be_returned boolean NOT NULL DEFAULT true,
  return_rules text NULL,
  storage_id uuid NULL,
  PRIMARY KEY (id)
);
