CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  cashier_id uuid NULL,
  total_amount numeric NOT NULL DEFAULT 0,
  original_total_amount numeric NOT NULL DEFAULT 0,
  returned_amount numeric NOT NULL DEFAULT 0,
  return_status text NOT NULL DEFAULT 'none'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  origin text NULL DEFAULT 'pos'::text,
  currency text NOT NULL DEFAULT 'usd'::text,
  settlement_currency text NOT NULL DEFAULT 'usd'::text,
  currency_conversion_applied boolean NOT NULL DEFAULT true,
  payment_method text NULL DEFAULT 'cash'::text,
  is_returned boolean NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  return_reason text NULL,
  returned_at timestamp with time zone NULL,
  returned_by uuid NULL,
  system_verified boolean NULL,
  system_review_status text NULL,
  system_review_reason text NULL,
  sequence_id bigint NOT NULL,
  notes text NULL,
  updated_at timestamp with time zone NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT sales_return_status_check CHECK (return_status = ANY (ARRAY['none'::text, 'partial'::text, 'full'::text])),
  CONSTRAINT sales_returned_amount_check CHECK (returned_amount >= 0),
  CONSTRAINT sales_id_workspace_key UNIQUE (id, workspace_id),
  PRIMARY KEY (id)
);
