CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  cashier_id uuid NULL,
  total_amount numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NULL DEFAULT now(),
  origin text NULL DEFAULT 'pos'::text,
  currency text NOT NULL DEFAULT 'usd'::text,
  settlement_currency text NOT NULL DEFAULT 'usd'::text,
  exchange_source text NULL,
  exchange_rate numeric NULL,
  exchange_rate_timestamp timestamp with time zone NULL,
  exchange_rates jsonb NULL,
  payment_method text NULL DEFAULT 'cash'::text,
  is_returned boolean NULL DEFAULT false,
  return_reason text NULL,
  returned_at timestamp with time zone NULL,
  returned_by uuid NULL,
  system_verified boolean NULL DEFAULT true,
  system_review_status text NULL DEFAULT 'approved'::text,
  system_review_reason text NULL,
  sequence_id bigint NOT NULL,
  notes text NULL,
  updated_at timestamp with time zone NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (id)
);
