CREATE TABLE public.workspaces (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text NOT NULL DEFAULT generate_workspace_code(),
  created_at timestamp with time zone NULL DEFAULT now(),
  allow_pos boolean NOT NULL DEFAULT false,
  allow_customers boolean NOT NULL DEFAULT false,
  allow_orders boolean NOT NULL DEFAULT false,
  allow_invoices boolean NOT NULL DEFAULT false,
  is_configured boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone NULL,
  default_currency text NOT NULL DEFAULT 'usd'::text,
  iqd_display_preference text NOT NULL DEFAULT 'IQD'::text,
  eur_conversion_enabled boolean NULL DEFAULT false,
  try_conversion_enabled boolean NULL DEFAULT false,
  locked_workspace boolean NULL DEFAULT false,
  max_discount_percent integer NULL DEFAULT 100,
  logo_url text NULL,
  allow_whatsapp boolean NULL DEFAULT false,
  member_count integer NULL DEFAULT 0,
  allow_suppliers boolean NOT NULL DEFAULT true,
  print_lang text NULL DEFAULT 'auto'::text,
  print_qr boolean NULL DEFAULT false,
  subscription_expires_at timestamp with time zone NULL,
  receipt_template text NULL DEFAULT 'primary'::text,
  a4_template text NULL DEFAULT 'primary'::text,
  print_quality text NULL DEFAULT 'low'::text,
  coordination text NULL,
  kds_enabled boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);
