export { Dashboard } from './Dashboard'
export { Login } from './Login'
export { Register } from './Register'
export { Products } from './Products'
export { InvoicesHistory } from './InvoicesHistory'
export { Members } from './Members'
export { Settings } from './Settings'
export { Admin } from './Admin'
export { WorkspaceRegistration } from './WorkspaceRegistration'
export { POS } from './POS'
export { Sales } from './Sales'
export { Loans } from './Loans'
export { MonthlyComparison } from './MonthlyComparison'
export { Budget } from './Budget'
export { WorkspaceConfiguration } from './WorkspaceConfiguration'
export { default as WhatsAppWeb } from './WhatsAppWeb'
