import {
  CreditCard,
  ArrowRightLeft,
  UsersRound,
  UserRound,
  Users,
  Truck,
  ShoppingCart,
  ClipboardCheck,
  Store,
  FileSpreadsheet,
  FileText,
  HandCoins,
  Building2,
  Copy,
  Wallet,
  Boxes,
  History,
  Warehouse,
  Percent,
  BarChart3,
  TrendingUp,
  Globe,
  Undo2,
  Receipt,
  CalendarClock,
  MapPinned,
  PackageCheck,
  History as RouteHistory,
  Car,
  Plane,
  Link2,
  Trash2,
  Coins,
} from "lucide-react";

export const WORKSPACE_PERMISSION_DEFINITIONS = [
  {
    key: "travelTransportation.access",
    module: "travelTransportation",
    labelKey: "travelTransportation.permissions.access",
    defaultLabel: "Travel & Transportation",
    descriptionKey: "travelTransportation.permissions.accessDescription",
    defaultDescription: "Access travel bookings, passenger records, and profit payment collection.",
    icon: Plane,
    section: "sell-and-serve",
  },
  {
    key: "carRental.access",
    module: "carRental",
    labelKey: "members.permissions.carRentalAccess",
    defaultLabel: "Car Rental Service",
    descriptionKey: "members.permissions.carRentalAccessDescription",
    defaultDescription: "Access rental vehicles, requests, contracts, and rental payments.",
    icon: Car,
    section: "sell-and-serve",
  },
  {
    key: "postService.access",
    module: "postService",
    labelKey: "members.permissions.postServiceAccess",
    defaultLabel: "Post Service",
    descriptionKey: "members.permissions.postServiceAccessDescription",
    defaultDescription: "Access delivery merchants, shipments, dispatch, and settlement views.",
    icon: PackageCheck,
    section: "agents",
  },
  {
    key: "postService.view_own",
    module: "postService",
    labelKey: "members.permissions.postServiceViewOwn",
    defaultLabel: "View Own Records",
    descriptionKey: "members.permissions.postServiceViewOwnDescription",
    defaultDescription: "Show only posts assigned to this member's linked courier.",
    icon: PackageCheck,
    section: "agents",
  },
  {
    key: "postService.dispatch",
    module: "postService",
    labelKey: "members.permissions.postServiceDispatch",
    defaultLabel: "Dispatch shipments",
    descriptionKey: "members.permissions.postServiceDispatchDescription",
    defaultDescription: "Create courier manifests and assign shipments to couriers.",
    icon: Truck,
    section: "agents",
  },
  {
    key: "postService.settle",
    module: "postService",
    labelKey: "members.permissions.postServiceSettle",
    defaultLabel: "Settle delivery cash",
    descriptionKey: "members.permissions.postServiceSettleDescription",
    defaultDescription: "Record courier handovers and merchant payouts.",
    icon: Wallet,
    section: "cash-and-control",
  },
  {
    key: "payment.access",
    module: "payment",
    labelKey: "members.permissions.paymentAccess",
    defaultLabel: "Payment module",
    descriptionKey: "members.permissions.paymentAccessDescription",
    defaultDescription: "Access the central payments page.",
    icon: CreditCard,
    section: "cash-and-control",
  },
  {
    key: "paymentAccounts.access",
    module: "paymentAccounts",
    labelKey: "members.permissions.paymentAccountsAccess",
    defaultLabel: "Payment Accounts",
    descriptionKey: "members.permissions.paymentAccountsAccessDescription",
    defaultDescription: "Access payment accounts, balances, and account movement history.",
    icon: Wallet,
    section: "cash-and-control",
  },
  {
    key: "paymentAccounts.manageCapitalPools",
    module: "paymentAccounts",
    labelKey: "members.permissions.paymentAccountsManageCapitalPools",
    defaultLabel: "Manage Capital Pools",
    descriptionKey: "members.permissions.paymentAccountsManageCapitalPoolsDescription",
    defaultDescription: "Create, edit, and delete Capital Pools inside Payment Accounts.",
    icon: Coins,
    section: "cash-and-control",
  },
  {
    key: "cashierShiftControl.access",
    module: "cashierShiftControl",
    labelKey: "members.permissions.cashierShiftControlAccess",
    defaultLabel: "Cashier Shift Control",
    descriptionKey: "members.permissions.cashierShiftControlAccessDescription",
    defaultDescription: "Manage cashier shift templates, assignments, and eligible shift starts.",
    icon: CalendarClock,
    section: "cash-and-control",
  },
  {
    key: "directTransaction.access",
    module: "directTransaction",
    labelKey: "members.permissions.directTransactionAccess",
    defaultLabel: "Direct Transaction module",
    descriptionKey: "members.permissions.directTransactionAccessDescription",
    defaultDescription: "Access manual incoming and outgoing transactions.",
    icon: ArrowRightLeft,
    section: "cash-and-control",
  },
  {
    key: "businessPartners.access",
    module: "businessPartners",
    labelKey: "members.permissions.businessPartnersAccess",
    defaultLabel: "Business Partners",
    descriptionKey: "members.permissions.businessPartnersAccessDescription",
    defaultDescription: "Access business partner records and balances.",
    icon: UsersRound,
    section: "partners-and-demand",
  },
  {
    key: "agents.access",
    module: "agents",
    labelKey: "members.permissions.agentsAccess",
    defaultLabel: "Agents",
    descriptionKey: "members.permissions.agentsAccessDescription",
    defaultDescription: "Access operational agents, drivers, territories, and linked workspace users.",
    icon: UserRound,
    section: "agents",
  },
  {
    key: "salesAgentCommissions.viewOwn",
    module: "salesAgentCommissions",
    labelKey: "members.permissions.salesAgentCommissionsViewOwn",
    defaultLabel: "View own commissions",
    descriptionKey: "members.permissions.salesAgentCommissionsViewOwnDescription",
    defaultDescription: "View orders assigned to this member's linked field agent and the resulting commission ledger. Agents and Sale Order access are also required.",
    icon: Percent,
    section: "agents",
  },
  {
    key: "salesAgentCommissions.viewAll",
    module: "salesAgentCommissions",
    labelKey: "members.permissions.salesAgentCommissionsViewAll",
    defaultLabel: "View all commissions",
    descriptionKey: "members.permissions.salesAgentCommissionsViewAllDescription",
    defaultDescription: "View commission performance, assignments, and ledger entries for every sales agent. Agents and Sale Order access are also required.",
    icon: BarChart3,
    section: "agents",
  },
  {
    key: "salesAgentCommissions.managePlans",
    module: "salesAgentCommissions",
    labelKey: "members.permissions.salesAgentCommissionsManagePlans",
    defaultLabel: "Manage commission plans",
    descriptionKey: "members.permissions.salesAgentCommissionsManagePlansDescription",
    defaultDescription: "Create effective-dated levels and assign commission memberships to field agents. Agents access is also required.",
    icon: Percent,
    section: "agents",
  },
  {
    key: "salesAgentCommissions.assignOrders",
    module: "salesAgentCommissions",
    labelKey: "members.permissions.salesAgentCommissionsAssignOrders",
    defaultLabel: "Assign sales orders",
    descriptionKey: "members.permissions.salesAgentCommissionsAssignOrdersDescription",
    defaultDescription: "Assign or reassign a sales order to a field agent and record its delivery snapshots. Sale Order Access is also required.",
    icon: Link2,
    section: "agents",
  },
  {
    key: "salesAgentCommissions.pay",
    module: "salesAgentCommissions",
    labelKey: "members.permissions.salesAgentCommissionsPay",
    defaultLabel: "Settle and recover commissions",
    descriptionKey: "members.permissions.salesAgentCommissionsPayDescription",
    defaultDescription: "Approve commission accruals, record adjustments, pay agents, and collect overpaid commission. Agents and Sale Order access are also required.",
    icon: Wallet,
    section: "cash-and-control",
  },
  {
    key: "fleet.access",
    module: "fleet",
    labelKey: "members.permissions.fleetAccess",
    defaultLabel: "Fleet Management",
    descriptionKey: "members.permissions.fleetAccessDescription",
    defaultDescription: "Access fleet vehicles, assignments, and operational views.",
    icon: MapPinned,
    section: "agents",
  },
  {
    key: "fleet.viewLiveLocations",
    module: "fleet",
    labelKey: "members.permissions.fleetViewLiveLocations",
    defaultLabel: "View live agent locations",
    descriptionKey: "members.permissions.fleetViewLiveLocationsDescription",
    defaultDescription: "View location-enabled agents on the live fleet map.",
    icon: MapPinned,
    section: "agents",
  },
  {
    key: "fleet.viewHistory",
    module: "fleet",
    labelKey: "members.permissions.fleetViewHistory",
    defaultLabel: "View location history",
    descriptionKey: "members.permissions.fleetViewHistoryDescription",
    defaultDescription: "Review sampled agent movement history.",
    icon: RouteHistory,
    section: "agents",
  },
  {
    key: "fleet.manageVehicles",
    module: "fleet",
    labelKey: "members.permissions.fleetManageVehicles",
    defaultLabel: "Manage fleet vehicles",
    descriptionKey: "members.permissions.fleetManageVehiclesDescription",
    defaultDescription: "Create, update, and retire fleet vehicles.",
    icon: Car,
    section: "agents",
  },
  {
    key: "fleet.manageAssignments",
    module: "fleet",
    labelKey: "members.permissions.fleetManageAssignments",
    defaultLabel: "Manage vehicle assignments",
    descriptionKey: "members.permissions.fleetManageAssignmentsDescription",
    defaultDescription: "Assign vehicles to agents and end active assignments.",
    icon: Link2,
    section: "agents",
  },
  {
    key: "fleet.shareLocation",
    module: "fleet",
    labelKey: "members.permissions.fleetShareLocation",
    defaultLabel: "Share My Location",
    descriptionKey: "members.permissions.fleetShareLocationDescription",
    defaultDescription: "Share device location to track agent position in real time.",
    icon: MapPinned,
    section: "agents",
  },
  {
    key: "customers.access",
    module: "customers",
    labelKey: "members.permissions.customersAccess",
    defaultLabel: "Customers",
    descriptionKey: "members.permissions.customersAccessDescription",
    defaultDescription: "Access customer records and details.",
    icon: Users,
    section: "partners-and-demand",
  },
  {
    key: "suppliers.access",
    module: "suppliers",
    labelKey: "members.permissions.suppliersAccess",
    defaultLabel: "Suppliers",
    descriptionKey: "members.permissions.suppliersAccessDescription",
    defaultDescription: "Access supplier records and details.",
    icon: Truck,
    section: "partners-and-demand",
  },
  {
    key: "orders.saleOrdersAccess",
    module: "orders",
    labelKey: "members.permissions.saleOrdersAccess",
    defaultLabel: "Sale Order Access",
    descriptionKey: "members.permissions.saleOrdersAccessDescription",
    defaultDescription: "Access sales orders.",
    icon: ShoppingCart,
    section: "partners-and-demand",
  },
  {
    key: "orders.purchaseOrdersAccess",
    module: "orders",
    labelKey: "members.permissions.purchaseOrdersAccess",
    defaultLabel: "Purchase Order Access",
    descriptionKey: "members.permissions.purchaseOrdersAccessDescription",
    defaultDescription: "Access purchase orders.",
    icon: Truck,
    section: "partners-and-demand",
  },
  {
    key: "orders.view_own",
    module: "orders",
    labelKey: "members.permissions.ordersViewOwn",
    defaultLabel: "View Own Records",
    descriptionKey: "members.permissions.ordersViewOwnDescription",
    defaultDescription: "Show only sales and purchase orders created by this member.",
    icon: History,
    section: "partners-and-demand",
  },
  {
    key: "orders.requireSalesOrderRequest",
    module: "orders",
    labelKey: "members.permissions.requireSalesOrderRequest",
    defaultLabel: "Require sales order requests",
    descriptionKey: "members.permissions.requireSalesOrderRequestDescription",
    defaultDescription: "Force this member to request admin approval before a sales order is saved as a normal draft.",
    icon: ClipboardCheck,
    section: "partners-and-demand",
  },
  {
    key: "orders.requirePurchaseOrderRequest",
    module: "orders",
    labelKey: "members.permissions.requirePurchaseOrderRequest",
    defaultLabel: "Require purchase order requests",
    descriptionKey: "members.permissions.requirePurchaseOrderRequestDescription",
    defaultDescription: "Force this member to request admin approval before a purchase order is saved as a normal draft.",
    icon: ClipboardCheck,
    section: "partners-and-demand",
  },
  {
    key: "ecommerce.access",
    module: "ecommerce",
    labelKey: "members.permissions.ecommerceAccess",
    defaultLabel: "E-Commerce",
    descriptionKey: "members.permissions.ecommerceAccessDescription",
    defaultDescription: "Access marketplace orders and e-commerce operations.",
    icon: Store,
    section: "partners-and-demand",
  },
  {
    key: "accounting.access",
    module: "accounting",
    labelKey: "members.permissions.accountingAccess",
    defaultLabel: "Accounting",
    descriptionKey: "members.permissions.accountingAccessDescription",
    defaultDescription: "Access accounting records and budget controls.",
    icon: FileSpreadsheet,
    section: "cash-and-control",
  },
  {
    key: "invoiceHistory.access",
    module: "invoiceHistory",
    labelKey: "members.permissions.invoiceHistoryAccess",
    defaultLabel: "Invoice History & Upload Files",
    descriptionKey: "members.permissions.invoiceHistoryAccessDescription",
    defaultDescription: "Access invoice history and uploaded invoice files.",
    icon: FileText,
    section: "cash-and-control",
  },
  {
    key: "invoice_history.view_own",
    module: "invoice_history",
    labelKey: "members.permissions.invoiceHistoryViewOwn",
    defaultLabel: "View Own Records",
    descriptionKey: "members.permissions.invoiceHistoryViewOwnDescription",
    defaultDescription: "Show only invoice history and uploaded files created by this member.",
    icon: FileText,
    section: "cash-and-control",
  },
  {
    key: "loans.access",
    module: "loans",
    labelKey: "members.permissions.loansAccess",
    defaultLabel: "Loans",
    descriptionKey: "members.permissions.loansAccessDescription",
    defaultDescription: "Access loan records and histories.",
    icon: HandCoins,
    section: "cash-and-control",
  },
  {
    key: "loans.view_own",
    module: "loans",
    labelKey: "members.permissions.loansViewOwn",
    defaultLabel: "View Own Records",
    descriptionKey: "members.permissions.loansViewOwnDescription",
    defaultDescription: "Show only simple loan records created by this member.",
    icon: HandCoins,
    section: "cash-and-control",
  },
  {
    key: "realEstate.access",
    module: "realEstate",
    labelKey: "members.permissions.realEstateAccess",
    defaultLabel: "Real Estate",
    descriptionKey: "members.permissions.realEstateAccessDescription",
    defaultDescription: "Access property transactions, balances, and installment schedules.",
    icon: Building2,
    section: "real-estate",
  },
  {
    key: "activities.access",
    module: "activities",
    labelKey: "activities.permissions.access",
    defaultLabel: "Activities",
    descriptionKey: "activities.permissions.accessDescription",
    defaultDescription: "Access the Activities module.",
    icon: CalendarClock,
    section: "sell-and-serve",
  },
  {
    key: "activities.manageCatalog",
    module: "activities",
    labelKey: "activities.permissions.manageCatalog",
    defaultLabel: "Manage activity catalog",
    descriptionKey: "activities.permissions.manageCatalogDescription",
    defaultDescription: "Create, edit, activate, and deactivate activities and their availability.",
    icon: ClipboardCheck,
    section: "sell-and-serve",
  },
  {
    key: "activities.createTransaction",
    module: "activities",
    labelKey: "activities.permissions.createTransaction",
    defaultLabel: "Sell activities in POS",
    descriptionKey: "activities.permissions.createTransactionDescription",
    defaultDescription: "Sell paid activities from the Activities storage in POS.",
    icon: CreditCard,
    section: "sell-and-serve",
  },
  {
    key: "activities.viewHistory",
    module: "activities",
    labelKey: "activities.permissions.viewHistory",
    defaultLabel: "View activity history",
    descriptionKey: "activities.permissions.viewHistoryDescription",
    defaultDescription: "View saved activity transactions and their price overrides.",
    icon: History,
    section: "sell-and-serve",
  },
  {
    key: "activities.print",
    module: "activities",
    labelKey: "activities.permissions.print",
    defaultLabel: "Print activity receipts",
    descriptionKey: "activities.permissions.printDescription",
    defaultDescription: "Print the custom Activities receipt.",
    icon: Receipt,
    section: "sell-and-serve",
  },
  {
    key: "activities.editTransaction",
    module: "activities",
    labelKey: "activities.permissions.editTransaction",
    defaultLabel: "Edit activity transactions",
    descriptionKey: "activities.permissions.editTransactionDescription",
    defaultDescription: "Edit completed activity transactions and their line prices.",
    icon: FileText,
    section: "sell-and-serve",
  },
  {
    key: "activities.refundTransaction",
    module: "activities",
    labelKey: "activities.permissions.refundTransaction",
    defaultLabel: "Cancel or refund activity transactions",
    descriptionKey: "activities.permissions.refundTransactionDescription",
    defaultDescription: "Cancel or refund a completed activity transaction and restore finite availability.",
    icon: Undo2,
    section: "sell-and-serve",
  },
  {
    key: "activities.deleteTransaction",
    module: "activities",
    labelKey: "activities.permissions.deleteTransaction",
    defaultLabel: "Hard-delete activity transactions",
    descriptionKey: "activities.permissions.deleteTransactionDescription",
    defaultDescription: "Permanently delete an activity transaction after the protected UI confirmation.",
    icon: Trash2,
    section: "sell-and-serve",
  },
  {
    key: "currencyExchange.access",
    module: "currencyExchange",
    labelKey: "members.permissions.currencyExchangeAccess",
    defaultLabel: "Currency Exchange Service",
    descriptionKey: "members.permissions.currencyExchangeAccessDescription",
    defaultDescription: "Access walk-in currency exchange transaction creation and history.",
    icon: ArrowRightLeft,
    section: "currency-exchange",
  },
  {
    key: "currencyExchangeFeeRules.access",
    module: "currencyExchangeFeeRules",
    labelKey: "members.permissions.currencyExchangeFeeRulesAccess",
    defaultLabel: "Fee/Commission Rules",
    descriptionKey: "members.permissions.currencyExchangeFeeRulesAccessDescription",
    defaultDescription: "Access reusable currency exchange fee and commission rules.",
    icon: Percent,
    section: "currency-exchange",
  },
  {
    key: "currencyExchange.managePrices",
    module: "currencyExchange",
    labelKey: "members.permissions.currencyExchangeManagePrices",
    defaultLabel: "Manage FX Prices",
    descriptionKey: "members.permissions.currencyExchangeManagePricesDescription",
    defaultDescription: "Edit manual buy and sell prices for currency exchange pairs.",
    icon: TrendingUp,
    section: "currency-exchange",
  },
  {
    key: "currencyExchange.reverse",
    module: "currencyExchange",
    labelKey: "members.permissions.currencyExchangeReverse",
    defaultLabel: "Reverse Transactions",
    descriptionKey: "members.permissions.currencyExchangeReverseDescription",
    defaultDescription: "Allows reversing exchange transactions, restoring safe balances to their prior state.",
    icon: Undo2,
    section: "currency-exchange",
  },
  {
    key: "clinicalAppointments.access",
    module: "clinicalAppointments",
    labelKey: "members.permissions.clinicalAppointmentsAccess",
    defaultLabel: "Clinical Appointments",
    descriptionKey: "members.permissions.clinicalAppointmentsAccessDescription",
    defaultDescription: "Access clinical appointments module.",
    icon: CalendarClock,
    section: "clinic-service",
  },
  {
    key: "clinicalPatients.access",
    module: "clinicalPatients",
    labelKey: "members.permissions.clinicalPatientsAccess",
    defaultLabel: "Patients",
    descriptionKey: "members.permissions.clinicalPatientsAccessDescription",
    defaultDescription: "Access patient records and details.",
    icon: Users,
    section: "clinic-service",
  },
  {
    key: "installments.access",
    module: "installments",
    labelKey: "members.permissions.installmentsAccess",
    defaultLabel: "Installments",
    descriptionKey: "members.permissions.installmentsAccessDescription",
    defaultDescription: "Access installment schedules and collection flow.",
    icon: Copy,
    section: "cash-and-control",
  },
  {
    key: "installments.view_own",
    module: "installments",
    labelKey: "members.permissions.installmentsViewOwn",
    defaultLabel: "View Own Records",
    descriptionKey: "members.permissions.installmentsViewOwnDescription",
    defaultDescription: "Show only installment records created by this member.",
    icon: Copy,
    section: "cash-and-control",
  },
  {
    key: "ledger.access",
    module: "ledger",
    labelKey: "members.permissions.ledgerAccess",
    defaultLabel: "Ledger",
    descriptionKey: "members.permissions.ledgerAccessDescription",
    defaultDescription: "Access ledger and cross-module financial trails.",
    icon: Wallet,
    section: "cash-and-control",
  },
  {
    key: "stockAdjustments.access",
    module: "stockAdjustments",
    labelKey: "members.permissions.stockAdjustmentsAccess",
    defaultLabel: "Stock Adjustments",
    descriptionKey: "members.permissions.stockAdjustmentsAccessDescription",
    defaultDescription: "Access stock adjustment records.",
    icon: Boxes,
    section: "stock-and-supply",
  },
  {
    key: "inventoryTransactions.access",
    module: "inventoryTransactions",
    labelKey: "members.permissions.inventoryTransactionsAccess",
    defaultLabel: "Inventory Transactions",
    descriptionKey: "members.permissions.inventoryTransactionsAccessDescription",
    defaultDescription: "Access inventory movement and transaction logs.",
    icon: History,
    section: "stock-and-supply",
  },
  {
    key: "inventoryTransfer.access",
    module: "inventoryTransfer",
    labelKey: "members.permissions.inventoryTransferAccess",
    defaultLabel: "Inventory Transfer",
    descriptionKey: "members.permissions.inventoryTransferAccessDescription",
    defaultDescription: "Access inventory transfer workflows.",
    icon: ArrowRightLeft,
    section: "stock-and-supply",
  },
  {
    key: "storages.access",
    module: "storages",
    labelKey: "members.permissions.storagesAccess",
    defaultLabel: "Storages",
    descriptionKey: "members.permissions.storagesAccessDescription",
    defaultDescription: "Access warehouses and storage locations.",
    icon: Warehouse,
    section: "stock-and-supply",
  },
  {
    key: "discounts.access",
    module: "discounts",
    labelKey: "members.permissions.discountsAccess",
    defaultLabel: "Discounts",
    descriptionKey: "members.permissions.discountsAccessDescription",
    defaultDescription: "Access discount and promotion controls.",
    icon: Percent,
    section: "stock-and-supply",
  },
  {
    key: "revenueAnalytics.access",
    module: "revenueAnalytics",
    labelKey: "members.permissions.revenueAnalyticsAccess",
    defaultLabel: "Revenue Analytics",
    descriptionKey: "members.permissions.revenueAnalyticsAccessDescription",
    defaultDescription: "Access revenue analytics and reporting.",
    icon: BarChart3,
    section: "insights-and-trends",
  },
  {
    key: "teamPerformance.access",
    module: "teamPerformance",
    labelKey: "members.permissions.teamPerformanceAccess",
    defaultLabel: "Team Performance",
    descriptionKey: "members.permissions.teamPerformanceAccessDescription",
    defaultDescription: "Access team performance reporting.",
    icon: TrendingUp,
    section: "people-and-workspace",
  },
  {
    key: "hr.access",
    module: "hr",
    labelKey: "members.permissions.hrAccess",
    defaultLabel: "HR",
    descriptionKey: "members.permissions.hrAccessDescription",
    defaultDescription: "Access HR records and workflows.",
    icon: UsersRound,
    section: "people-and-workspace",
  },
  {
    key: "global.NOprint",
    module: "global",
    labelKey: "members.permissions.globalPrint",
    defaultLabel: "Print",
    descriptionKey: "members.permissions.globalPrintDescription",
    defaultDescription: "Allow printing across all modules by default.",
    icon: Globe,
    section: "global",
  },
  {
    key: "global.hideCosts",
    module: "global",
    labelKey: "members.permissions.globalHideCosts",
    defaultLabel: "Hide Costs",
    descriptionKey: "members.permissions.globalHideCostsDescription",
    defaultDescription: "Hide product costs and order profit information for this member.",
    icon: Wallet,
    section: "global",
  },
  {
    key: "manualEntry.access",
    module: "manualEntry",
    labelKey: "members.permissions.manualEntryAccess",
    defaultLabel: "Manual Entry",
    descriptionKey: "members.permissions.manualEntryAccessDescription",
    defaultDescription: "Access manual entry creation and history.",
    icon: FileText,
    section: "manual-entry",
  },
  {
    key: "manualEntryTemplates.access",
    module: "manualEntryTemplates",
    labelKey: "members.permissions.manualEntryTemplatesAccess",
    defaultLabel: "Manual Entry Templates",
    descriptionKey: "members.permissions.manualEntryTemplatesAccessDescription",
    defaultDescription: "Access manual entry template management.",
    icon: FileSpreadsheet,
    section: "manual-entry",
  },
  {
    key: "pos.access",
    module: "pos",
    labelKey: "members.permissions.posAccess",
    defaultLabel: "POS",
    descriptionKey: "members.permissions.posAccessDescription",
    defaultDescription: "Access the point-of-sale checkout flow.",
    icon: CreditCard,
    section: "sell-and-serve",
  },
  {
    key: "pos.hideModifyPriceButton",
    module: "pos",
    labelKey: "members.permissions.posHideModifyPriceButton",
    defaultLabel: "Hide Modify price button",
    descriptionKey: "members.permissions.posHideModifyPriceButtonDescription",
    defaultDescription: "Hide the pencil icon to modify item prices in the POS cart.",
    icon: CreditCard,
    section: "sell-and-serve",
  },
  {
    key: "pos.hidePriceBelowCostIndicator",
    module: "pos",
    labelKey: "members.permissions.posHidePriceBelowCostIndicator",
    defaultLabel: 'Hide "Price is Below cost" indicator',
    descriptionKey: "members.permissions.posHidePriceBelowCostIndicatorDescription",
    defaultDescription: 'Hide the warning indicator when the negotiated price is below cost inside the Modify Price modal.',
    icon: CreditCard,
    section: "sell-and-serve",
  },
  {
    key: "instantPos.access",
    module: "instantPos",
    labelKey: "members.permissions.instantPosAccess",
    defaultLabel: "Instant POS",
    descriptionKey: "members.permissions.instantPosAccessDescription",
    defaultDescription: "Access the rapid-service fast lane POS.",
    icon: ArrowRightLeft,
    section: "sell-and-serve",
  },
  {
    key: "salesHistory.access",
    module: "salesHistory",
    labelKey: "members.permissions.salesHistoryAccess",
    defaultLabel: "Sales History",
    descriptionKey: "members.permissions.salesHistoryAccessDescription",
    defaultDescription: "Access completed sales, returns, and sales records.",
    icon: History,
    section: "sell-and-serve",
  },
  {
    key: "sales.view_own",
    module: "sales",
    labelKey: "members.permissions.salesViewOwn",
    defaultLabel: "View Own Records",
    descriptionKey: "members.permissions.salesViewOwnDescription",
    defaultDescription: "Show only completed sales created by this member.",
    icon: History,
    section: "sell-and-serve",
  },
  {
    key: "products.access",
    module: "products",
    labelKey: "members.permissions.productsAccess",
    defaultLabel: "Products",
    descriptionKey: "members.permissions.productsAccessDescription",
    defaultDescription: "Access the product catalog, stock rules, and pricing.",
    icon: ShoppingCart,
    section: "stock-and-supply",
  },
  {
    key: "budget.access",
    module: "budget",
    labelKey: "members.permissions.budgetAccess",
    defaultLabel: "Budget",
    descriptionKey: "members.permissions.budgetAccessDescription",
    defaultDescription: "Access accounting records, budgets, and financial controls.",
    icon: Wallet,
    section: "cash-and-control",
  },
] as const;

export type WorkspacePermissionKey =
  (typeof WORKSPACE_PERMISSION_DEFINITIONS)[number]["key"];

const supportedPermissionKeys = new Set<string>(
  WORKSPACE_PERMISSION_DEFINITIONS.map((permission) => permission.key),
);

export function isSupportedWorkspacePermissionKey(
  key: string,
): key is WorkspacePermissionKey {
  return supportedPermissionKeys.has(key);
}

export function getWorkspacePermissionModule(key: string) {
  return key.split(".")[0] || key;
}
